name:  CI pull request workflow

on:
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v7

    - name: Setup pnpm
      uses: pnpm/action-setup@v6
      with:
        version: 9
        run_install: false

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version-file: '.nvmrc'
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install

    - name: Run lint
      run: pnpm lint

    - name: Built app
      run: pnpm build